
###
POST http://localhost:8081/user
Content-Type: application/json

{
    "name": "Jeferson Schlarski",
    "email": "jeferson@gmail.com",
    "type": 1,
    "phone": "48991650106",
    "cpf": "1142335591",
    "password": "teste123" 
}

###
POST http://localhost:8081/auth
Content-Type: application/json

{
    "email": "jeferson@gmail.com",
    "password": "teste123" 
}

###
GET http://localhost:8081/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjQ3MzUxODQsInVzZXJJZCI6MX0.gzng-WvwwVStWe0ltBNq-LhlRZ269u8Z3DFYl7ZweW8

###
GET http://localhost:8081/city
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjQ3MzUxODQsInVzZXJJZCI6MX0.gzng-WvwwVStWe0ltBNq-LhlRZ269u8Z3DFYl7ZweW8

###
GET http://localhost:8081/city/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjQ3MzUxODQsInVzZXJJZCI6MX0.gzng-WvwwVStWe0ltBNq-LhlRZ269u8Z3DFYl7ZweW8


###
GET http://localhost:8081/state/2/city
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjQ3MzUxODQsInVzZXJJZCI6MX0.gzng-WvwwVStWe0ltBNq-LhlRZ269u8Z3DFYl7ZweW8


#   Complement string `json:"complement,omitempty"`
#   Number     uint64 `json:"number,omitempty"`
#   Cep        string `json:"cep,omitempty"`
#   CityID     uint64 `json:"city_id,omitempty"`

###
POST http://localhost:8081/address
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjQ3MzUxODQsInVzZXJJZCI6MX0.gzng-WvwwVStWe0ltBNq-LhlRZ269u8Z3DFYl7ZweW8
Content-Type: application/json

{
    "complement": "Testando criação",
    "number": 110,
    "cep": "88105304",
    "city_id": 1
}

###
GET http://localhost:8081/address
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjQ3MzUxODQsInVzZXJJZCI6MX0.gzng-WvwwVStWe0ltBNq-LhlRZ269u8Z3DFYl7ZweW8



