
###
POST http://localhost:8081/user
Content-Type: application/json

{
    "name": "Jeferson Schlarski",
    "email": "jeferson@gmail.com",
    "phone": "+5548991650106",
    "cpf": "11423133951",
    "password": "teste123" 
}

###
POST http://localhost:8081/auth
Content-Type: application/json

{
    "email": "jeferson@gmail.com",
    "password": "teste123" 
}

###
GET http://localhost:8081/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjY5NzI4MzIsInVzZXJJZCI6MX0.wocCj_7XSj60MNuqkKVLL2U6_2eEhNfsspV4MRmvCFg

###
GET http://localhost:8081/city
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjY5NzI4MzIsInVzZXJJZCI6MX0.wocCj_7XSj60MNuqkKVLL2U6_2eEhNfsspV4MRmvCFg

###
GET http://localhost:8081/city/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjY5NzI4MzIsInVzZXJJZCI6MX0.wocCj_7XSj60MNuqkKVLL2U6_2eEhNfsspV4MRmvCFg


###
GET http://localhost:8081/state/1/city
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjY5NzI4MzIsInVzZXJJZCI6MX0.wocCj_7XSj60MNuqkKVLL2U6_2eEhNfsspV4MRmvCFg

#   Complement string `json:"complement,omitempty"`
#   Number     uint64 `json:"number,omitempty"`
#   Cep        string `json:"cep,omitempty"`
#   CityID     uint64 `json:"city_id,omitempty"`

###
POST http://localhost:8081/address
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjY5NzI4MzIsInVzZXJJZCI6MX0.wocCj_7XSj60MNuqkKVLL2U6_2eEhNfsspV4MRmvCFg
Content-Type: application/json

{
    "complement": "Testando criação",
    "number": 110,
    "cep": "88105304",
    "city_id": 1
}

###
GET http://localhost:8081/address
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE3MjY5NzI4MzIsInVzZXJJZCI6MX0.wocCj_7XSj60MNuqkKVLL2U6_2eEhNfsspV4MRmvCFg



