[database]
host = "localhost"
port = "5433"
user = "admin"
pass = "admin"
name = "database"
drive = "postgres"

[api]
url = "localhost"
port = 8080

[auth]
key = "SSbw4fKgoUPHS75Epjz1g2R/AOd5ZTonG9At5UNZaSZiIHhKf7nw/a1BaTDHeasX+e8pfxCsrKIrkaB2kfrZLA=="