[database]
host = "localhost"
port = "5432"
user = "postgres"
pass = "pg@syS"
name = "postgres"
drive = "postgres"

[api]
url = "localhost"
port = 8080

[auth]
key = "SSbw4fKgoUPHS75Epjz1g2R/AOd5ZTonG9At5UNZaSZiIHhKf7nw/a1BaTDHeasX+e8pfxCsrKIrkaB2kfrZLA=="